name: 'Run PHPUnit Tests'

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'PHPUnit Tests'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.6
        ports:
          - '3306:3306'
        env:
          MYSQL_ROOT_PASSWORD: root
          MARIADB_INITDB_SKIP_TZINFO: 1
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysql, mysqli
          coverage: none

      - name: 'Why do not composer install'
        run: |
          : # Do not install Composer dependencies becuase we are included vendor dir
  
      - name: 'Set up WordPress test environment'
        uses: sjinks/setup-wordpress-test-library@master
        with:
          version: latest
          db_user: wordpress
          db_password: wordpress
          db_name: wordpress_test
          db_host: 127.0.0.1:${{ job.services.mysql.ports[3306] }}

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h 127.0.0.1 -P ${{ job.services.mysql.ports[3306] }} --silent; do
            sleep 1
          done
        timeout-minutes: 1

      - name: 'Run PHPUnit tests'
        run: vendor/bin/phpunit
        env:
          WP_PHPUNIT_TESTS_CONFIG_PATH: ${{ env.WP_TESTS_DIR }}/wp-tests-config.php
